<?php
    $data = $this->getAllStatistics();
    $attacks = $data['attacks'];
    $percent = $data['percent'];
    $years = $data['years'];
    $selected = $data['selected'];

    if(empty($attacks[$selected]['datasets']) && empty($percent[$selected]['datasets'])){
        echo "<div>".$this->__("There are no records")."</div>";
    } else {
?>
        <div style="width: 100%; height: 40px; float: left;">
            <label for="year">Choose a Year:</label>
            <select id="year" class="select">
                <?php
                    foreach ($years as $value){
                        $attr = ($value == $selected)?'selected':'';
                        echo "<option value='$value' $attr>$value</option>";
                    }
                ?>

            </select>
            <button title="load" type="button" class="scalable" onclick="setData()"><span><span><span>Load Data</span></span></span></button>
            <button title="clean" type="button" class="scalable" onclick="cleanData()"><span><span><span>Clean Data</span></span></span></button>
        </div>
        <div style="width: 100%; min-height: 300px; float: left;">
            <div style="width: 50%; height: auto; float: left;">
                <h2><?php echo $this->__("Attack statistics"); ?></h2>
                <canvas id="line_chart_canvas"></canvas>
            </div>
            <div style="width: 50%; height: auto; float: right;">
                <h2><?php echo $this->__("Percentage of attacks"); ?></h2>
                <canvas id="pie_chart_canvas"></canvas>
            </div>
        </div>

        <script>
            var year = <?php echo $selected;?>;
            var attacks = <?php echo json_encode($attacks)?>;
            var percent = <?php echo json_encode($percent)?>;
            var years = ['<?php echo $selected; ?>'];

            var line_chart_canvas = document.getElementById("line_chart_canvas");
            var line_chart = new Chart(line_chart_canvas, {
                type: 'line',
                data: {
                    labels: attacks[year].labels,
                    datasets: attacks[year].datasets
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero:true,
                                userCallback: function(label, index) {
                                    if (Math.floor(label) === label) {
                                        return label;
                                    }
                                }
                            },
                            scaleLabel: {
                                display: true,
                                labelString: '<?php echo $this->__('Attacks'); ?>'
                            }
                        }],

                        xAxes: [{
                            scaleLabel: {
                                display: true,
                                labelString: '<?php echo $this->__('Months'); ?>'
                            }
                        }]
                    },
                    responsive: true
                }
            });

            var pie_chart_canvas = document.getElementById("pie_chart_canvas");
            var my_chart = new Chart(pie_chart_canvas, {
                type: 'pie',
                data: {
                    datasets: [{
                        data: percent[year].datasets.data,
                        backgroundColor: percent[year].datasets.backgroundColor,
                        label: percent[year].datasets.label
                    }],
                    labels: percent[year].labels
                },
                options: {
                    responsive: true
                }
            });

            function setData() {
                var yearSelected= document.getElementById('year').value;

                if (yearSelected == year) {
                    alert(<?php echo $this->__("It's the same year. Please, select other.");?>);
                } else if (years.indexOf(yearSelected) !== -1) {
                    alert(<?php echo $this->__("The data is already loaded.");?>);
                } else {
                    year = yearSelected;
                    years.push(year);

                    var dataChart = [{
                        data: percent[year].datasets.data,
                        backgroundColor: percent[year].datasets.backgroundColor,
                        label: percent[year].datasets.label
                    }];

                    my_chart.data.datasets = [...my_chart.data.datasets, ...dataChart];
                    var dataLine = [...line_chart.data.datasets, ...attacks[year].datasets];
                    line_chart.data.datasets = dataLine;

                    my_chart.update();
                    line_chart.update();
                }
            }

            function cleanData() {
                my_chart.data.datasets = [];
                line_chart.data.datasets = [];
                years = [];
                year = '';

                my_chart.update();
                line_chart.update();
            }
        </script>
<?php
    }
?>

